---
- name: Install Blackbox Exporter
  hosts: tag_  # Adjust to your target hosts group
  become: yes  # Ensure the tasks are run with sudo
  vars:
    blackbox_exporter_version: '0.25.0'  # Adjust to the desired Blackbox Exporter version
    blackbox_exporter_user: 'prometheus'
    blackbox_exporter_service: '/etc/systemd/system/blackbox_exporter.service'
  tasks:
    - name: Create a blackbox_exporter user
      user:
        name: "{{ blackbox_exporter_user }}"
        shell: /usr/sbin/nologin

    - name: Download Blackbox Exporter
      get_url:
        url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/blackbox_exporter.tar.gz

    - name: Extract Blackbox Exporter
      unarchive:
        src: /tmp/blackbox_exporter.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Rename extracted directory
      command: mv /opt/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64 /opt/blackbox_exporter

    - name: Set ownership to blackbox_exporter user
      file:
        path: /opt/blackbox_exporter
        state: directory
        owner: "{{ blackbox_exporter_user }}"
        group: "{{ blackbox_exporter_user }}"
        recurse: yes
    - name: Create systemd service file for Blackbox Exporter
      copy:
        dest: "/opt/blackbox_exporter/blackbox.yml"
        content: |
          modules:
            tcp_connect:
              prober: tcp
              timeout: 5s
              tcp:
                query_response:
                  - expect: ".*"


    - name: Create systemd service file for Blackbox Exporter
      copy:
        dest: "{{ blackbox_exporter_service }}"
        content: |
          [Unit]
          Description=Blackbox Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ blackbox_exporter_user }}
          ExecStart=/opt/blackbox_exporter/blackbox_exporter --config.file /opt/blackbox_exporter/blackbox.yml

          [Install]
          WantedBy=default.target

    - name: Reload systemd to apply changes
      command: systemctl daemon-reload

    - name: Enable and start Blackbox Exporter service
      systemd:
        name: blackbox_exporter
        enabled: yes
        state: started

